
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/admin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 显示慢sql 默认当超过3秒显示
          log-slow-sql: true
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
admin:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 默认JWT 启用Redis后设置为true后，token将存入redis，并具有单点登录功能
    redis: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  mob:
    appKey: 297e77269e800
# 忽略鉴权url
ignored:
  urls:
  - /editor-app/**
  - /admin/file/view/**
  - /admin/user/regist
  - /admin/user/smsLogin
  - /admin/user/resetByMobile
  - /admin/common/**
  - /druid/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /swagger/**
  - /**/v2/api-docs
  - /**/*.js
  - /**/*.css
  - /**/*.png
  - /**/*.ico
  - /test/**
# Swagger界面内容配置
swagger:
  title: Admin API接口文档
  description: Admin Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://www.baidu.com
  contact:
    name: 小胡
    url: http://www.baidu.com
    email: 775771672@qq.com
pagehelper:
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  row-bounds-with-count: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:modules/**/*.xml
  type-aliases-package: com.software.manager.biz.modules
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
# 日志
logging:
  file: logs/log.log
  level:
     com.software.manager.biz: debug
